### ISSUE TITLE
linkStyle prop not used

### ISSUE THREAD

**Issue by EHadoux** [ssthouse/tree-chart#115]
Hey, thanks again for the Vue3 version. 
It looks like the `linkStyle` prop is not used, it always draws curved lines.
https://github.com/ssthouse/tree-chart/blob/432c94165192b0befed1240132f8ec3580c1ef89/packages/vue3-tree-chart/src/vue-tree/VueTree.vue#L107-L114
That might be where it's missing. Reverting to 0.1.0 worked though.

**Comment by ssthouse** [comment]
Hi, sorry for the late reply.

This issue has been fixed in `v0.2.5`, please check.

**Comment by kortykotropina** [comment]
Hi!
This issue isn't fixed. I fixed it in this PR - https://github.com/ssthouse/tree-chart/pull/121

**Comment by ssthouse** [comment]
> Hi! This issue isn't fixed. I fixed it in this PR - #121

Oh, thank you! 

I released your fix in `v0.2.6` please check @kortykotropina @EHadoux

**Comment by EHadoux** [comment]
Yep, seems to be fixed, thanks!
