### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by Linus-Boehm** [ssthouse/tree-chart#25]
Hey ssthouse,
thanks for your efforts on this library.
I would like to use this package in typescript project, but unfortunately there are no types included in the npm package and the `VueTree.vue` is by itself a normal js file. 

Do you accept PRs for migrating the `VueTree.vue` and emitting the types?

**Comment by ssthouse** [comment]
sure, actually I have the plan to add type support but didn't spare any time yet~

I will be glad to have your support👏
